package Common;

/** 
 * Message types
 * 
 * @author Rodrigo Santos
 * @author Alexey Kononov
 *  
 */
public enum MessageType {

	// PILOT
	PILOT_INFORM_READY_FOR_BOARDING, PILOT_WAITING_FOR_BOARDING, PILOT_FLYING_FORWARD, PILOT_FLYING_BACK, PILOT_PARKING_AT_GATE, PILOT_DEBOARDING,
	
	// HOSTESS
	HOSTESS_WAITING_FOR_FLIGHT, HOSTESS_WAITING_FOR_PASSENGER, HOSTESS_INFORM_READY_TO_FLY, HOSTESS_CHECK_PASSENGER, HOSTESS_PREPARE_FOR_PASS_BOARDING  ,
	
	// PASSENGER
	PASSENGER_GOING_TO_AIRPORT, PASSENGER_IN_QUEUE, PASSENGER_IN_FLIGHT, PASSENGER_AT_DESTINATION,PASSENGER_SHOW_DOCS, PASSENGER_BOARDING_PLANE,
	PASSENGER_LEAVING_PLANE, PASSENGER_WAITS_IN_QUEUE,PASSENGER_IN_PLANE,
	
	// SHARED REGIONS
	SIM_ENDED,GET_PTAL,CAN_TAKE_OFF,GET_IN_FLIGHT, SET_IN_FLIGHT,SET_PLANE_EMPTY,
	
	// REPOSITORY
	UPDATE_PASSENGER_STATE, UPDATE_HOSTESS_STATE, UPDATE_PILOT_STATE, INIT, FINISH, UPDATE_INQ, UPDATE_INF, UPDATE_PTAL, LOG_UPD,GET_FLIGHT,
    
	//GENERAL
	OK
}
